
----ADMINS TABLE
--insert into admins (username , password ,name)
--values ( 'adm1' , '$2a$12$zf/xQmgOilOlFgiZylI/veC2SWmgcNUYbpnsBwL4dFu0sjun4xD2C' , 'Nikola Nikolic');
--insert into admins (username , password ,name)
--values ('adm2' , '$2a$12$zf/xQmgOilOlFgiZylI/veC2SWmgcNUYbpnsBwL4dFu0sjun4xD2C' , 'Petar Peric');
--insert into admins (username , password ,name)
--values ( 'adm3' , '$2a$12$zf/xQmgOilOlFgiZylI/veC2SWmgcNUYbpnsBwL4dFu0sjun4xD2C' , 'Zarko Dragic' );
--insert into admins (username , password ,name)
--values ( 'adm44' , '$2a$12$zf/xQmgOilOlFgiZylI/veC2SWmgcNUYbpnsBwL4dFu0sjun4xD2C' , 'Dobrosav Drazenovic');
--insert into admins (username , password ,name)
--values ( 'adm55' , '$2a$12$zf/xQmgOilOlFgiZylI/veC2SWmgcNUYbpnsBwL4dFu0sjun4xD2C' , 'Nino Ninic');